services:
  autoindex:
    image: "ghcr.io/skyone-wzw/nginx-autoindex:v1.3.0"
    restart: unless-stopped
    #environment:
    #  SITECONFIG_NAME: "File Sharing"
    #  SITECONFIG_TITLE:
    #  SITECONFIG_FOOTER:
    #  SITECONFIG_README: true
    #  SITECONFIG_BEFORE: true
    volumes:
      - "./data:/var/www/html"
    ports:
      - "80:80"
